#
# Jekyll configuration
#
#exclude: ["vendor"]

markdown: kramdown

encoding: utf-8

collections:
    kits:
            output: true
            permalink: /:path/index:output_ext

versions:
- iOS8
- iOS7
- iOS6
- iOS5
- iOS4
- iOS3
- iOS2
- iOS1