#
# Jekyll configuration
#
#exclude: ["vendor"]

markdown: kramdown

encoding: utf-8

collections:
    ios:
            output: true
            permalink: /:path/index:output_ext
    kits:
            output: true
            permalink: /:path/index:output_ext

versions:
- iOS2
- iOS3
- iOS4
- iOS5
- iOS6
- iOS7
- iOS8